server {
    listen 80;
    server_name _;

    root /var/www/loadtest;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
    
    location ~* \.(js|css|jpg|png)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    }
}